import {
  CheckSquare2,
  ClipboardCheck,
  Timer,
  Undo2,
  XCircle,
} from "lucide-react";

export interface ITransaction {
  bookingCode: string;
  touristName: string;
  tourPackage: string;
  duration: string;
  price: number;
  status: "approved" | "pending" | "refund" | "refunded" | "canceled";
}

export const transactionData: ITransaction[] = [
  {
    bookingCode: "INV01091001",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091002",
    touristName: "Rizky",
    tourPackage: "Korea",
    duration: "5 days 4 night",
    price: 24000000,
    status: "canceled",
  },
  {
    bookingCode: "INV01091003",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "refund",
  },
  {
    bookingCode: "INV01091004",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "refunded",
  },
  {
    bookingCode: "INV01091005",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091006",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091007",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091008",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091009",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091010",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091011",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091012",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091013",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091014",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091015",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091016",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091017",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091018",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091019",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091020",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091021",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091022",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091023",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "approved",
  },
  {
    bookingCode: "INV01091024",
    touristName: "Maman",
    tourPackage: "Japan",
    duration: "5 days 4 night",
    price: 24000000,
    status: "pending",
  },
];

export const statuses = [
  {
    value: "approved",
    label: "Approved",
    icon: CheckSquare2,
  },
  {
    value: "pending",
    label: "Pending",
    icon: Timer,
  },
  {
    value: "refund",
    label: "Refund",
    icon: Undo2,
  },
  {
    value: "refunded",
    label: "Refunded",
    icon: ClipboardCheck,
  },
  {
    value: "canceled",
    label: "Canceled",
    icon: XCircle,
  },
];
